# Основные настройки
title: "Портфолио"
description: "Эссе, заметки и проекты"
url: "https://zhenyacode.github.io"
baseurl: ""

# Коллекции
collections:
  essays:
    output: true
    permalink: /essays/:path/
  projects:
    output: true
    permalink: /projects/:path/

# Настройки по умолчанию
defaults:
  - scope:
      path: ""
      type: "essays"
    values:
      layout: "essay"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "default"

future: true

# Markdown
markdown: kramdown
kramdown:
  input: GFM